### ISSUE TITLE
GreenDAO faster than SQLite

### ISSUE THREAD

**Issue by benwicks** [AlexeyZatsepin/Android-ORM-benchmark#2]
Why do you think GreenDAO was faster than SQLite in this benchmark?

**Comment by AlexeyZatsepin** [comment]
Proceeding from the resulting table - GreenDAO is faster only in the recording of the complex and balanced case. I think, it can be caused because GreenDAO works more optimally with foreign keys than we do in our implementation of SQLite flavor. (we have explicit link to other model, except id)

**Comment by benwicks** [comment]
👍  That makes sense. Thanks! I'm using your benchmark in a presentation. It has been really helpful!

**Comment by AlexeyZatsepin** [comment]
Thanks for your feedback 👍
